version: 2.1

description: |
  mojaloop/pr-tools is a CircleCI orb for convenience functions and utilities in Mojaloop CI/CD pipelines

executors:
  default:
    working_directory: /home/circleci/project
    docker:
      - image: node:12.16.1-alpine

commands:
  pr-title-check:
    description: Check the title of a Github pull request
    # parameters:
    steps:
      - run:
          name: Install general dependencies
          command: |
            apk --no-cache add git \
              ca-certificates \
              curl \
              openssh-client \
              build-dependencies \
              make \
              gcc \
              g++ \
              libtool \
              autoconf \
              automake \
              jq
      # Orbs don't let you package anything more than basic shell scripts
      # so we bootstrap this orb by checking out the code in the repo
      # TODO: checkout based on deterministic git tag
      - run:
          name: checkout ci-config repo
          command: |
            git clone -b feat/pr-title-orb https://github.com/mojaloop/ci-config.git
            cd ci-config/pr-tools && npm install
      - run:
          name: Check the PR title
          command: |
            echo "env CIRCLE_PULL_REQUESTS: ${CIRCLE_PULL_REQUESTS}"
            echo "env CIRCLE_PULL_REQUEST: ${CIRCLE_PULL_REQUEST}"
            cd ci-config &&  ./pr-tools/_pr_title.js

jobs:
  pr-title-check:
    executors: default
    steps:
      - pr-title-check
